
################################################################################
# This file was auto-generated by avx2_codegen_batch.py
# The loop is unrolled 256 times
################################################################################


# the System V AMD64 ABI says that :
# A) The first six integer or pointer arguments are passed in registers RDI, RSI, RDX, RCX, R8, R9
# B) we should preserve the values of %rbx, %rbp, %r12...%r15 [callee-save registers]
# C) We will receive the arguments of the function in registers :
#       Fq           in %rdi
#       Fl           in %rsi
#       alpha        in %rdx
#       beta         in %rcx
#       gamma        in %r8
# D) we return the mask in %rax

# no need to save the callee-save registers (we do not touch them)
# Load the 13 most used values into %ymm0-%ymm12
# %ymm15 is pinned to zero
# %ymm14 is used for temporary storage (could be dispensed with)
# %ymm13 contains the mask

# we may still use %9, %r10 and %r11
# %r11 contains the comparison output mask 
# %r9 and %r10 are available

# This uses only "light" AVX2 instructions (no FP, no MUL). But cores runs at "AVX2" speed.
# Scheduling on Haswell : each step is 4 instructions ;
#   three steps send 4 uops to ports 0,1,5  (in the best case)
#   three steps thus take at least 4 cycles
#   peak performance is then 16x3 candidates in 4 cycles --> 12 candidates/cycle
# 
# Measured : 5.75 cycles for three steps without hyperthreading
# Measured : 4.45 cycles for three steps with hyperthreading
#
# This is a 35% speedup wrt the non-batch version. Even with 10% additionnal work afterwards, there is a clear gain.

### extern u32 feslite_avx2_asm_enum_batch(const __m256i * Fq, __m256i * Fl, u64 alpha, u64 beta, u64 gamma)

.text
.p2align 5

.globl feslite_avx2_asm_enum_batch
feslite_avx2_asm_enum_batch:

# multiply alpha, beta, gamma by 32
shlq $5, %rdx
shlq $5, %rcx
shlq $5, %r8

vpxor %ymm15, %ymm15, %ymm15         # set %ymm15 to always-zero
vpxor %ymm13, %ymm13, %ymm13         # initialize acc (%ymm13) to zero

movq %r9, %rax                       # prepare the return value

# load the most-frequently used values into vector registers
vmovdqa 0(%rsi), %ymm0   ## %ymm0 = Fl[0]
vmovdqa 32(%rsi), %ymm1   ## %ymm1 = Fl[1]
vmovdqa 64(%rsi), %ymm2   ## %ymm2 = Fl[2]
vmovdqa 96(%rsi), %ymm3   ## %ymm3 = Fl[3]
vmovdqa 128(%rsi), %ymm4   ## %ymm4 = Fl[4]
vmovdqa 160(%rsi), %ymm5   ## %ymm5 = Fl[5]
vmovdqa 192(%rsi), %ymm6   ## %ymm6 = Fl[6]

vmovdqa 0(%rdi), %ymm7   ## %ymm7 = Fq[0]
vmovdqa 32(%rdi), %ymm8   ## %ymm8 = Fq[1]
vmovdqa 64(%rdi), %ymm9   ## %ymm9 = Fq[2]
vmovdqa 96(%rdi), %ymm10   ## %ymm10 = Fq[3]
vmovdqa 128(%rdi), %ymm11   ## %ymm11 = Fq[4]
vmovdqa 160(%rdi), %ymm12   ## %ymm12 = Fq[5]


##### step   0 : Fl[0] ^= (Fl[1] ^= Fq[alpha + 0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 0(%rdi, %rdx), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step   1 : Fl[0] ^= (Fl[2] ^= Fq[alpha + 1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 32(%rdi, %rdx), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step   2 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step   3 : Fl[0] ^= (Fl[3] ^= Fq[alpha + 2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 64(%rdi, %rdx), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step   4 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step   5 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step   6 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step   7 : Fl[0] ^= (Fl[4] ^= Fq[alpha + 3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 96(%rdi, %rdx), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step   8 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step   9 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  10 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  11 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  12 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  13 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  14 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  15 : Fl[0] ^= (Fl[5] ^= Fq[alpha + 4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 128(%rdi, %rdx), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step  16 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  17 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  18 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  19 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  20 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  21 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  22 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  23 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step  24 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  25 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  26 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  27 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  28 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  29 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  30 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  31 : Fl[0] ^= (Fl[6] ^= Fq[alpha + 5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 160(%rdi, %rdx), %ymm6, %ymm6
vpxor %ymm6, %ymm0, %ymm0


##### step  32 : Fl[0] ^= (Fl[1] ^= Fq[10])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 320(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  33 : Fl[0] ^= (Fl[2] ^= Fq[11])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 352(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  34 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  35 : Fl[0] ^= (Fl[3] ^= Fq[12])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 384(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  36 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  37 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  38 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  39 : Fl[0] ^= (Fl[4] ^= Fq[13])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 416(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step  40 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  41 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  42 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  43 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  44 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  45 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  46 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  47 : Fl[0] ^= (Fl[5] ^= Fq[14])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 448(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step  48 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  49 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  50 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  51 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  52 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  53 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  54 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  55 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step  56 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  57 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  58 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  59 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  60 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  61 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  62 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  63 : Fl[0] ^= (Fl[7] ^= Fq[alpha + 6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vmovdqa 224(%rsi), %ymm14
vpxor 192(%rdi, %rdx), %ymm14, %ymm14
vmovdqa %ymm14, 224(%rsi)
vpxor %ymm14, %ymm0, %ymm0


##### step  64 : Fl[0] ^= (Fl[1] ^= Fq[15])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 480(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  65 : Fl[0] ^= (Fl[2] ^= Fq[16])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 512(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  66 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  67 : Fl[0] ^= (Fl[3] ^= Fq[17])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 544(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  68 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  69 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  70 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  71 : Fl[0] ^= (Fl[4] ^= Fq[18])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 576(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step  72 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  73 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  74 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  75 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  76 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  77 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  78 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  79 : Fl[0] ^= (Fl[5] ^= Fq[19])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 608(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step  80 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  81 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  82 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  83 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  84 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  85 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  86 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  87 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step  88 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  89 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  90 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  91 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step  92 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  93 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  94 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  95 : Fl[0] ^= (Fl[6] ^= Fq[20])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 640(%rdi), %ymm6, %ymm6
vpxor %ymm6, %ymm0, %ymm0


##### step  96 : Fl[0] ^= (Fl[1] ^= Fq[10])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 320(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  97 : Fl[0] ^= (Fl[2] ^= Fq[11])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 352(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step  98 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step  99 : Fl[0] ^= (Fl[3] ^= Fq[12])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 384(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 100 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 101 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 102 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 103 : Fl[0] ^= (Fl[4] ^= Fq[13])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 416(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 104 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 105 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 106 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 107 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 108 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 109 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 110 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 111 : Fl[0] ^= (Fl[5] ^= Fq[14])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 448(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step 112 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 113 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 114 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 115 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 116 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 117 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 118 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 119 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 120 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 121 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 122 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 123 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 124 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 125 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 126 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 127 : Fl[0] ^= (Fl[8] ^= Fq[alpha + 7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vmovdqa 256(%rsi), %ymm14
vpxor 224(%rdi, %rdx), %ymm14, %ymm14
vmovdqa %ymm14, 256(%rsi)
vpxor %ymm14, %ymm0, %ymm0


##### step 128 : Fl[0] ^= (Fl[1] ^= Fq[21])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 672(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 129 : Fl[0] ^= (Fl[2] ^= Fq[22])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 704(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 130 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 131 : Fl[0] ^= (Fl[3] ^= Fq[23])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 736(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 132 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 133 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 134 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 135 : Fl[0] ^= (Fl[4] ^= Fq[24])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 768(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 136 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 137 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 138 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 139 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 140 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 141 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 142 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 143 : Fl[0] ^= (Fl[5] ^= Fq[25])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 800(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step 144 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 145 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 146 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 147 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 148 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 149 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 150 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 151 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 152 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 153 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 154 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 155 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 156 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 157 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 158 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 159 : Fl[0] ^= (Fl[6] ^= Fq[26])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 832(%rdi), %ymm6, %ymm6
vpxor %ymm6, %ymm0, %ymm0


##### step 160 : Fl[0] ^= (Fl[1] ^= Fq[10])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 320(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 161 : Fl[0] ^= (Fl[2] ^= Fq[11])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 352(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 162 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 163 : Fl[0] ^= (Fl[3] ^= Fq[12])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 384(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 164 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 165 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 166 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 167 : Fl[0] ^= (Fl[4] ^= Fq[13])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 416(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 168 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 169 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 170 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 171 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 172 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 173 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 174 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 175 : Fl[0] ^= (Fl[5] ^= Fq[14])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 448(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step 176 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 177 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 178 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 179 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 180 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 181 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 182 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 183 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 184 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 185 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 186 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 187 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 188 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 189 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 190 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 191 : Fl[0] ^= (Fl[7] ^= Fq[27])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vmovdqa 224(%rsi), %ymm14
vpxor 864(%rdi), %ymm14, %ymm14
vmovdqa %ymm14, 224(%rsi)
vpxor %ymm14, %ymm0, %ymm0


##### step 192 : Fl[0] ^= (Fl[1] ^= Fq[15])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 480(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 193 : Fl[0] ^= (Fl[2] ^= Fq[16])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 512(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 194 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 195 : Fl[0] ^= (Fl[3] ^= Fq[17])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 544(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 196 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 197 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 198 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 199 : Fl[0] ^= (Fl[4] ^= Fq[18])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 576(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 200 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 201 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 202 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 203 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 204 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 205 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 206 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 207 : Fl[0] ^= (Fl[5] ^= Fq[19])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 608(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step 208 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 209 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 210 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 211 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 212 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 213 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 214 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 215 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 216 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 217 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 218 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 219 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 220 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 221 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 222 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 223 : Fl[0] ^= (Fl[6] ^= Fq[20])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 640(%rdi), %ymm6, %ymm6
vpxor %ymm6, %ymm0, %ymm0


##### step 224 : Fl[0] ^= (Fl[1] ^= Fq[10])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 320(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 225 : Fl[0] ^= (Fl[2] ^= Fq[11])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 352(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 226 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 227 : Fl[0] ^= (Fl[3] ^= Fq[12])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 384(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 228 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 229 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 230 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 231 : Fl[0] ^= (Fl[4] ^= Fq[13])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 416(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 232 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 233 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 234 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 235 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 236 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 237 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 238 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 239 : Fl[0] ^= (Fl[5] ^= Fq[14])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 448(%rdi), %ymm5, %ymm5
vpxor %ymm5, %ymm0, %ymm0


##### step 240 : Fl[0] ^= (Fl[1] ^= Fq[6])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 192(%rdi), %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 241 : Fl[0] ^= (Fl[2] ^= Fq[7])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 224(%rdi), %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 242 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 243 : Fl[0] ^= (Fl[3] ^= Fq[8])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 256(%rdi), %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 244 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 245 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 246 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 247 : Fl[0] ^= (Fl[4] ^= Fq[9])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor 288(%rdi), %ymm4, %ymm4
vpxor %ymm4, %ymm0, %ymm0


##### step 248 : Fl[0] ^= (Fl[1] ^= Fq[3])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm10, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 249 : Fl[0] ^= (Fl[2] ^= Fq[4])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm11, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 250 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 251 : Fl[0] ^= (Fl[3] ^= Fq[5])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm12, %ymm3, %ymm3
vpxor %ymm3, %ymm0, %ymm0


##### step 252 : Fl[0] ^= (Fl[1] ^= Fq[1])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm8, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0


##### step 253 : Fl[0] ^= (Fl[2] ^= Fq[2])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm9, %ymm2, %ymm2
vpxor %ymm2, %ymm0, %ymm0


##### step 254 : Fl[0] ^= (Fl[1] ^= Fq[0])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vpxor %ymm7, %ymm1, %ymm1
vpxor %ymm1, %ymm0, %ymm0

#############################
# end of the unrolled chunk #
#############################

# Save the Fl[1:] back to memory
vmovdqa %ymm1, 32(%rsi)     #Fl[1] <-- %ymm1
vmovdqa %ymm2, 64(%rsi)     #Fl[2] <-- %ymm2
vmovdqa %ymm3, 96(%rsi)     #Fl[3] <-- %ymm3
vmovdqa %ymm4, 128(%rsi)     #Fl[4] <-- %ymm4
vmovdqa %ymm5, 160(%rsi)     #Fl[5] <-- %ymm5
vmovdqa %ymm6, 192(%rsi)     #Fl[6] <-- %ymm6

##### special last step 255 : Fl[0] ^= (Fl[beta] ^= Fq[gamma])

vpcmpeqd %ymm0, %ymm15, %ymm15
vpor %ymm15, %ymm13, %ymm13
vmovdqa (%rsi, %rcx), %ymm14
vpxor (%rdi, %r8), %ymm14, %ymm14
vmovdqa %ymm14, (%rsi, %rcx)
vpxor %ymm14, %ymm0, %ymm0

# Save Fl[0] back to memory
vmovdqa %ymm0, (%rsi)     #Fl[0] <-- %ymm0

# Save acc back to memory
vpmovmskb %ymm13, %eax     #return value <-- %ymm13
ret

####################################################
# Stats
# reg / reg : 176
# mem / reg : 76
# mem / mem : 3
